spring:
  application:
    name: apigateway
  profiles:
    active: ${env.SPRING_PROFILES_ACTIVE:local}
app:
  gateway:
    auth-bypass: ${APP_GATEWAY_AUTH_BYPASS:false}
server:
  port: 8000

---
spring:
  config:
    activate:
      on-profile: local

    import:
      - optional:configserver:http://localhost:8888
      - optional:file:.env[.properties]

app:
  gateway:
    auth-bypass: false

---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - optional:configserver:http://config:8888
